"""add new field

Revision ID: 205b5017b38f
Revises: 16cb42551f1d
Create Date: 2023-04-17 06:22:18.889363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '205b5017b38f'
down_revision = '16cb42551f1d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'comment')
    # ### end Alembic commands ###
