"""add created_at field Post

Revision ID: 773ff9540f84
Revises: 45e052284f48
Create Date: 2023-04-14 05:43:43.588210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '773ff9540f84'
down_revision = '45e052284f48'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('created_at', sa.Date(), nullable=True))
    op.add_column('post_image', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_image', 'image')
    op.drop_column('post', 'created_at')
    # ### end Alembic commands ###
